version: '3.9'

services:
  express:
    build: ./app
    ports:
      - "5000:5000"
   
 
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
volumes:
 
